/*
 * ---------------------------------------------
 * Author: PJ Medina
 * Date:   Saturday July 1st 2023
 * Last Modified by: Rovelin Enriquez - <enriquezrovelin@gmail.com>
 * Last Modified time: July 6th 2023, 11:40:54 pm
 * ---------------------------------------------
 */

import AuthWrapper from '@/components/AuthWrapper';

import { Jost } from 'next/font/google';

const jost = Jost({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={jost.className} style={{ margin: 0, padding: 0 }}>
        <AuthWrapper>{children}</AuthWrapper>
      </body>
    </html>
  );
}
